releases/20150808023450/config/routes.rb
Rails.application.routes.draw do


  #get 'menus/show'


  mount Ckeditor::Engine => '/ckeditor'

  get 'posts/show'
  get 'posts/showalltintuc'
  get 'posts/showalltuyensinh'
  get 'posts/showalltuyendung'
  get 'posts/showallthongbao'
  get 'home/contact'
  # post 'admin/login' => 'sessions#create'
  # get 'admin/login' => 'sessions#create'

  # devise_scope :admin_user do
  #     get 'admin/login5' => 'sessions#new1', :as => :user_login
  #   end
  #get 'admin/login5' => 'sessions#new1'
ActiveAdmin.routes(self)
  #devise_for :admin_users do get '/amdin/login' => 'sessions#create' end
    
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  get 'home/index'

  resources :home
  resources :categories
  resources :contacts
  resources :menus , path: 'trang'

  get '/*id', to: 'posts#show', as: :post


  get 'tin-tuc/index'
  resources :pages, path: 'trang'
  
  root 'home#index'

end

releases/20150808023450/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
	belongs_to :page
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable, :lockable

end

releases/20150808023450/app/models/category.rb
class Category < ActiveRecord::Base
	include Sluggable
	has_many :posts
	validates :name, presence: true

end

releases/20150808023450/app/models/confighome.rb
class Confighome < ActiveRecord::Base
end

releases/20150808023450/app/models/contact.rb
# encoding: utf-8
class Contact < ActiveRecord::Base
  validates :name,
            :presence => {:message=>'Không được để trống họ tên.'},
            :length => { :minimum => 5 , :message => "Nhập tên nhiều hơn 5 ký tự."}
  validates :phone,
            :presence => {:message=>'Không được để trống số điện thoại.'},
            :length => { :minimum =>8,:maximum => 13, :message => "Nhập số điện thoại chưa đúng"}
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,:message => 'Email nhập chưa đúng'
  validates :subject,
            :presence => {:message=>'Không được để trống tiêu đề.'},
            :length => { :minimum => 5,:message=>'Nhập tiêu đề nhiều hơn 5 ký tự.' }
  validates :message,
            :presence =>{:message=>'Không được để trống nội dung.'},
            :length => { :minimum => 5,:message=>'Nhập tiêu đề nhiều hơn 5 ký tự.'}
end

releases/20150808023450/app/models/menu.rb
class Menu < ActiveRecord::Base
	has_one :page

	include Sluggable
end

releases/20150808023450/app/models/page.rb
class Page < ActiveRecord::Base
	has_many :admin_users
	has_many :posts
	belongs_to :menu
	validates :name, presence: true
	include Sluggable
	# acts_as_url :name, :sync_url => true, url_attribute: :url
	# def to_param
	#   "#{id}-#{url}"
	# end
end

releases/20150808023450/app/models/popup.rb
class Popup < ActiveRecord::Base
end

releases/20150808023450/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :category
	belongs_to :page
	belongs_to :admin_user
	has_attached_file :pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ActionController::Base.helpers.asset_path('imgpost.jpg')
  	validates_attachment_content_type :pic, :content_type => /^image\/(png|gif|jpeg)/
  	validates :name, presence: true
  	validates :summary, presence: true
  	validates :content, presence: true
  	validates :name, presence: true

	acts_as_url :name, :sync_url => true, :allow_slash => true, url_attribute: :url
	def to_param
	  "#{id}-#{self.page.url}/#{self.category.url}/#{url}"
	end
end

releases/20150808023450/app/models/slidercontent.rb
class Slidercontent < ActiveRecord::Base
  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
end

releases/20150808023450/app/models/videohd.rb
class Videohd < ActiveRecord::Base

end

releases/20150808023450/app/controllers/contacts_controller.rb
# encoding: utf-8
class ContactsController < ApplicationController
  def contact_params
    params.require(:contact).permit( :name, :email, :phone, :subject,:message)
  end
  def new
    @c=Contact.new
  end
  def create
    @c=Contact.new(contact_params)
    if verify_recaptcha
      if @c.save
        redirect_to new_contact_path, :notice => "Cảm ơn bạn đã gửi liên hệ!"
      else
        @error_string=""
        @c.errors.full_messages.each do |message|
          @error_string+=message+"<br>"
        end
        redirect_to new_contact_path,:flash => {  :error =>@error_string}
      end
    else

      flash[:error] = "Captcha nhập chưa đúng, Vui lòng nhập lại!"
      flash.delete(:recaptcha_error)
      render "new"
    end
  end

end

releases/20150808023450/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end



end

releases/20150808023450/app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def show
  	@menu =Menu.find(params[:id])

    @department=Page.where("menu_id=?", @menu.id).first
    @category=Category.joins(:posts).where("posts.page_id=?",@department.id).uniq
  end
end

releases/20150808023450/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    
    #@department=Department.find_by_url(params[:id])
    @department=Page.find(params[:id])
    @category=Category.joins(:posts).where("posts.page_id=? and categories.category_type=0",@department.id).uniq
    #@category=Category.joins(:posts).where("posts.department_id=?",@department.id).uniq
    #@category = Category.includes(:posts).select{|c| c.posts.where(['department_id = ?',@department.id])}
    #@category=Category.all
    #@post=Post.where("department_id=?",@department.id).order(created_at: :desc).limit(5)
    # @thongbao=Post.where("category_id = ? and department_id=?",2,@department.id).order(created_at: :desc).limit(5)
    # @tintuc=Post.where("category_id = ? and department_id=?",3,@department.id).order(created_at: :desc).limit(5)
    # @tuyendung=Post.where("category_id = ? and department_id=?",4,@department.id).order(created_at: :desc).limit(5)
    # @tuyensinh=Post.where("category_id = ? and department_id=?",1,@department.id).order(created_at: :desc).limit(5)
  end
end

releases/20150808023450/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def permitted_params
    params.permit post: [:title, :image,:content,:summary,:category_id, :author_id,:admin_user_id]
  end

  def show
    @post=Post.find(params[:id])
    @user=AdminUser.all
    @category=@post.category
    @allpost=@category.posts.where("id != ? and page_id=?",@post.id,@post.page_id).order(is_new: :desc, created_at: :desc).limit(5)
  end
  def showalltintuc
    @posttd=Post.where("category_id = ?",3).order(is_new: :desc, created_at: :desc).paginate(:page => params[:page], :per_page => 10)
  end
  def showallthongbao
    @posttd=Post.where("category_id = ?",2).order(is_new: :desc, created_at: :desc).paginate(:page => params[:page], :per_page => 10)

  end
  def showalltuyensinh
    @posttd=Post.where("category_id = ?",1).order(is_new: :desc, created_at: :desc).paginate(:page => params[:page], :per_page => 10)

  end
  def showalltuyendung
    @posttd=Post.where("category_id = ?",4).order(is_new: :desc, created_at: :desc).paginate(:page => params[:page], :per_page => 10)

  end
end

releases/20150808023450/app/helpers/application_helper.rb
module ApplicationHelper
end

releases/20150808023450/app/helpers/categories_helper.rb
module CategoriesHelper
end

releases/20150808023450/app/helpers/departments_helper.rb
module DepartmentsHelper
end

releases/20150808023450/app/helpers/home_helper.rb
module HomeHelper
end

releases/20150808023450/app/helpers/menus_helper.rb
module MenusHelper
end

releases/20150808023450/app/helpers/pages_helper.rb
module PagesHelper
end

releases/20150808023450/app/helpers/posts_helper.rb
module PostsHelper
end

releases/20150808023450/app/helpers/session_helper.rb
module SessionHelper
end

releases/20150808023450/app/views/menus/show.html.haml
%header#head.secondary
  .container
    %h1= @department.name
    %p= @department.slogan
%section.container{:style => "padding-top: 20px;"}
  .row
    %section.col-sm-8.maincontent
      = raw @department.description
    - @category.each do |cate|
      %aside.col-sm-4.sidebar.sidebar-right.box-shadow.box-radius{:style => "margin-top: 30px;"}
        - if !cate.posts.where("page_id=?",@department.id).empty?
          .panel
            %h4.tag-h4= cate.name
            %ul.list-unstyled.list-spaces
              - cate.posts.where("page_id=?",@department.id).each do |post|
                %li
                  = link_to post.name,post_path(post)
                  %br

releases/20150808023450/app/views/posts/show.html.haml
%header#head.secondary
  .container
    %h1{:style => "margin-top: 20px;"} TIN TỨC
%section.container
  .row
    / main content
    %section.col-sm-8.maincontent
      %h3= @post.name
      %small
        Ngày đăng :#{@post.created_at.strftime("%d/%m/%Y")}
      %p= raw(@post.content)
      %p{:style => "float:right;font-size:12px;font-weight:bold;"}
        Người đăng: #{@post.admin_user.name}
    - if @allpost.count >= 1
      %aside.col-sm-4.sidebar.sidebar-right.box-shadow.box-radius{:style => "margin-top: 30px;"}
        .panel
          %h4{:style => "background: #3D84E6 none repeat scroll 0% 0%;color: #FFF;padding: 10px;text-transform: uppercase;margin-top: 0px;"}= @category.name
          %ul.list-unstyled.list-spaces
            - @allpost.each do |post|
              %li= link_to post.name,post_path(post)

releases/20150808023450/app/views/posts/showallthongbao.html.haml
%header#head.secondary
  .container
    %h1{:style => "margin-top: 20px;"} THÔNG BÁO
%section.container
  .row{:style => "margin-top: 35px;"}
    / main content
    %aside.col-sm-12.sidebar.sidebar-right.box-shadow.box-radius
      .panel
        %ul.list-unstyled.list-spaces
          - @posttd.each do |tt|
            %li
              = link_to truncate(tt.name,:length=>75),post_path(tt)
              - if  tt.is_new?
                %span.new_class
            = image_tag tt.pic.url ,:class => "pic"
            = tt.summary
            %div{:style => "text-align: right;"}
              = link_to "Chi Tiết ...",posts_show_path(:id=>tt.id)
            %div{:style => "clear: both;"}
            %h1{:style => "border-bottom: 1px dotted #ccc"}
          .flickr_pagination
            = will_paginate @posttd

releases/20150808023450/app/views/posts/showalltintuc.html.haml
%header#head.secondary
  .container
    %h1{:style => "margin-top: 20px;"} TIN TỨC
%section.container
  .row{:style => "margin-top: 35px;"}
    / main content
    %aside.col-sm-12.sidebar.sidebar-right.box-shadow.box-radius
      .panel
        %ul.list-unstyled.list-spaces
          - @posttd.each do |tt|
            %li
              = link_to truncate(tt.name,:length=>75),post_path(tt)
              - if  tt.is_new?
                %span.new_class
            = image_tag tt.pic.url ,:class => "pic"
            = tt.summary
            %div{:style => "text-align: right;"}
              = link_to "Chi Tiết ...",posts_show_path(:id=>tt.id)
            %div{:style => "clear: both;"}
            %h1{:style => "border-bottom: 1px dotted #ccc"}
          .flickr_pagination
            = will_paginate @posttd

releases/20150808023450/app/views/posts/showalltuyendung.html.haml
%header#head.secondary
  .container
    %h1{:style => "margin-top: 20px;"} TUYỂN DỤNG
%section.container
  .row{:style => "margin-top: 35px;"}
    / main content
    %aside.col-sm-12.sidebar.sidebar-right.box-shadow.box-radius
      .panel
        %ul.list-unstyled.list-spaces
          - @posttd.each do |tt|
            %li
              = link_to truncate(tt.name,:length=>75),post_path(tt)
              - if  tt.is_new?
                %span.new_class
            = image_tag tt.pic.url ,:class => "pic"
            = tt.summary
            %div{:style => "text-align: right;"}
              = link_to "Chi Tiết ...",posts_show_path(:id=>tt.id)
            %div{:style => "clear: both;"}
            %h1{:style => "border-bottom: 1px dotted #ccc"}
          .flickr_pagination
            = will_paginate @posttd

releases/20150808023450/app/views/posts/showalltuyensinh.html.haml
%header#head.secondary
  .container
    %h1{:style => "margin-top: 20px;"} TUYỂN SINH
%section.container
  .row{:style => "margin-top: 35px;"}
    / main content
    %aside.col-sm-12.sidebar.sidebar-right.box-shadow.box-radius
      .panel
        %ul.list-unstyled.list-spaces
          - @posttd.each do |tt|
            %li
              = link_to truncate(tt.name,:length=>75),post_path(tt)
              - if  tt.is_new?
                %span.new_class
            = image_tag tt.pic.url ,:class => "pic"
            = tt.summary
            %div{:style => "text-align: right;"}
              = link_to "Chi Tiết ...",posts_show_path(:id=>tt.id)
            %div{:style => "clear: both;"}
            %h1{:style => "border-bottom: 1px dotted #ccc"}
          .flickr_pagination
            = will_paginate @posttd