releases/20150808023450/config/routes.rb
Rails.application.routes.draw do


  #get 'menus/show'


  mount Ckeditor::Engine => '/ckeditor'

  get 'posts/show'
  get 'posts/showalltintuc'
  get 'posts/showalltuyensinh'
  get 'posts/showalltuyendung'
  get 'posts/showallthongbao'
  get 'home/contact'
  # post 'admin/login' => 'sessions#create'
  # get 'admin/login' => 'sessions#create'

  # devise_scope :admin_user do
  #     get 'admin/login5' => 'sessions#new1', :as => :user_login
  #   end
  #get 'admin/login5' => 'sessions#new1'
ActiveAdmin.routes(self)
  #devise_for :admin_users do get '/amdin/login' => 'sessions#create' end
    
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  get 'home/index'

  resources :home
  resources :categories
  resources :contacts
  resources :menus , path: 'trang'

  get '/*id', to: 'posts#show', as: :post


  get 'tin-tuc/index'
  resources :pages, path: 'trang'
  
  root 'home#index'

end

releases/20150808023450/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
	belongs_to :page
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable, :lockable

end

releases/20150808023450/app/models/category.rb
class Category < ActiveRecord::Base
	include Sluggable
	has_many :posts
	validates :name, presence: true

end

releases/20150808023450/app/models/confighome.rb
class Confighome < ActiveRecord::Base
end

releases/20150808023450/app/models/contact.rb
# encoding: utf-8
class Contact < ActiveRecord::Base
  validates :name,
            :presence => {:message=>'Không được để trống họ tên.'},
            :length => { :minimum => 5 , :message => "Nhập tên nhiều hơn 5 ký tự."}
  validates :phone,
            :presence => {:message=>'Không được để trống số điện thoại.'},
            :length => { :minimum =>8,:maximum => 13, :message => "Nhập số điện thoại chưa đúng"}
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,:message => 'Email nhập chưa đúng'
  validates :subject,
            :presence => {:message=>'Không được để trống tiêu đề.'},
            :length => { :minimum => 5,:message=>'Nhập tiêu đề nhiều hơn 5 ký tự.' }
  validates :message,
            :presence =>{:message=>'Không được để trống nội dung.'},
            :length => { :minimum => 5,:message=>'Nhập tiêu đề nhiều hơn 5 ký tự.'}
end

releases/20150808023450/app/models/menu.rb
class Menu < ActiveRecord::Base
	has_one :page

	include Sluggable
end

releases/20150808023450/app/models/page.rb
class Page < ActiveRecord::Base
	has_many :admin_users
	has_many :posts
	belongs_to :menu
	validates :name, presence: true
	include Sluggable
	# acts_as_url :name, :sync_url => true, url_attribute: :url
	# def to_param
	#   "#{id}-#{url}"
	# end
end

releases/20150808023450/app/models/popup.rb
class Popup < ActiveRecord::Base
end

releases/20150808023450/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :category
	belongs_to :page
	belongs_to :admin_user
	has_attached_file :pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ActionController::Base.helpers.asset_path('imgpost.jpg')
  	validates_attachment_content_type :pic, :content_type => /^image\/(png|gif|jpeg)/
  	validates :name, presence: true
  	validates :summary, presence: true
  	validates :content, presence: true
  	validates :name, presence: true

	acts_as_url :name, :sync_url => true, :allow_slash => true, url_attribute: :url
	def to_param
	  "#{id}-#{self.page.url}/#{self.category.url}/#{url}"
	end
end

releases/20150808023450/app/models/slidercontent.rb
class Slidercontent < ActiveRecord::Base
  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
end

releases/20150808023450/app/models/videohd.rb
class Videohd < ActiveRecord::Base

end

releases/20150808023450/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end



end

releases/20150808023450/app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def show
  	@menu =Menu.find(params[:id])

    @department=Page.where("menu_id=?", @menu.id).first
    @category=Category.joins(:posts).where("posts.page_id=?",@department.id).uniq
  end
end

releases/20150808023450/app/helpers/application_helper.rb
module ApplicationHelper
end

releases/20150808023450/app/helpers/categories_helper.rb
module CategoriesHelper
end

releases/20150808023450/app/helpers/departments_helper.rb
module DepartmentsHelper
end

releases/20150808023450/app/helpers/home_helper.rb
module HomeHelper
end

releases/20150808023450/app/helpers/menus_helper.rb
module MenusHelper
end

releases/20150808023450/app/helpers/pages_helper.rb
module PagesHelper
end

releases/20150808023450/app/helpers/posts_helper.rb
module PostsHelper
end

releases/20150808023450/app/helpers/session_helper.rb
module SessionHelper
end

releases/20150808023450/app/views/pages/show.html.haml
%header#head.secondary
  .container
    %h1= @department.name
    %p= @department.slogan
%section.container
  .row
    %section.col-sm-8.maincontent
      = raw @department.description
    %aside.col-sm-4.sidebar.sidebar-right.box-shadow.box-radius{:style => "margin-top: 30px;"}
      - @category.each do |cate|
        - if !cate.posts.where("department_id=?",@department.id).empty?
          .panel
            %h4.tag-h4= cate.name
            %ul.list-unstyled.list-spaces
              - cate.posts.where("department_id=?",@department.id).each do |post|
                %li
                  = link_to post.name,post_path(post)
                  %br
                    %span.small.text-muted= post.summary

releases/20150808023450/app/views/partials/_container.html.haml
.container
  .row
    .col-md-3
      .grey-box-icon.border-box
        .box-vnits-tuyensinh
          %span.box-a Tuyển Sinh
        %ul.list-unstyled.list-spaces.text-left1
          - all_posts_tuyen_sinh.each do |post|
            %li{:style => "position:relative;"}
              = link_to truncate(post.name,:length=>75),post_path(post)
              - if  post.is_new?
                %span.new_class
        %p
          %em= link_to "Xem thêm ..." ,posts_showalltuyensinh_path
    .col-md-3
      .grey-box-icon
        .box-vnits-thongbao
          %span.box-a Thông Báo
        %ul.list-unstyled.list-spaces.text-left1
          - all_posts_thong_bao.each do |post|
            %li
              = link_to truncate(post.name,:length=>75),post_path(post)
              - if  post.is_new?
                %span.new_class
        %p
          %em= link_to "Xem thêm ..." ,posts_showallthongbao_path
    .col-md-3
      .grey-box-icon
        .box-vnits-tintuc
          %span.box-a Tin tức
        %ul.list-unstyled.list-spaces.text-left1
          - all_posts_tin_tuc.each do |post|
            %li
              = link_to truncate(post.name,:length=>75),post_path(post)
              - if  post.is_new?
                %span.new_class
        %p
          %em= link_to "Xem thêm ..." ,posts_showalltintuc_path
    .col-md-3
      .grey-box-icon
        .box-vnits-tuyendung
          %span.box-a Tuyển Dụng
        %ul.list-unstyled.list-spaces.text-left1
          - all_posts_tuyen_dung.each do |post|
            %li
              = link_to truncate(post.name,:length=>75),post_path(post)
              - if  post.is_new?
                %span.new_class
        %p
          %em= link_to "Xem thêm ..." ,posts_showalltuyendung_path

releases/20150808023450/app/views/partials/_footer.html.haml
%footer#footer
  .container
    .row
      .footerbottom
        .col-md-4.col-sm-6
          .footerwidget
            %h4{:style => "text-transform: uppercase;"}
              Đơn vị liên kết
            .menu-course
              %ul.menu
                %li
                  = link_to "Bộ Giáo Dục & Đào Tạo","http://www.moet.gov.vn",target:"_blank"
                %li
                  = link_to "Tổng Cục Dạy Nghề","http://tcdn.gov.vn",target:"_blank"
                %li
                  = link_to "UBND Quận Thủ Đức","http://www.thuduc.hochiminhcity.gov.vn",target:"_blank"
                %li
                  = link_to "Báo Giáo Dục Online","http://www.giaoduc.edu.vn",target:"_blank"
                %li
                  = link_to "Báo Dân Trí","http://dantri.com.vn",target:"_blank"
        .col-md-4.col-sm-6
          .footerwidget
            %h4 LIÊN HỆ
            %p Trường Trung Cấp Nghề Thủ Đức
            .contact-info
              - if cauhinh_trangchu
                - cauhinh_trangchu.each do |c|
                  %i.fa.fa-map-marker.fa-2x{:style => "color: #fb0a2a;"}
                  = raw(c.diachi)
                  %br
                    %i.fa.fa-phone.fa-2x{:style => "color: #34ad00;"}
                    = raw(c.phone)
                    %br
                      %i.fa.fa-envelope-o.fa-2x{:style => "color: #fcb314;"}
                      = raw(c.email)
                  
        .col-md-4.col-sm-6
          %div
            %h4 BẢN ĐỒ
            .contact-info
              .video-container
                %iframe{:height => "200", :src => "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3918.4457868917802!2d106.76601600000001!3d10.853659000000002!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3175279edf747bc1%3A0x1fb1f6f29f2cf70f!2zVHLGsOG7nW5nIFRydW5nIEPhuqVwIE5naOG7gSBUaOG7pyDEkOG7qWM!5e0!3m2!1svi!2s!4v1434771451847", :style => "border: 0;", :width => "390"}
          / end widget
    .social.text-center
      - if cauhinh_trangchu
        - cauhinh_trangchu.each do |c|
          %a{:href => raw(c.linktw)}
            %i.fa.fa-twitter{:style => "color: #5dd7fc"}
          %a{:href => raw(c.linkfb)}
            %i.fa.fa-facebook{:style => "color: rgb(59, 89, 152);"}
          %a{:href => "#"}
            %i.fa.fa-dribbble{:style => "color: #EA4C89;"}
          %a{:href => "#"}
            %i.fa.fa-flickr{:style => "color: #1f8dd6;"}
          %a{:href => "#"}
            %i.fa.fa-github{:style => "color: #ffa500;"}
      
    .clear
  .footer2
    .container
      .row
        .col-md-6.panel
          .panel-body
            %p.simplenav
              %a{:href => root_path} Trang Chủ
              |
              
              \#{link_to "Liên Hệ",:controller => "contacts",:action => "new"}
          .panel-body{:style => "padding-top: 10px;"}
            %p.simplenav
        .col-md-6.panel
          .panel-body
            %p.text-right
              - if cauhinh_trangchu.first
                = raw(cauhinh_trangchu.first.copyright)
#goTop.to-top
  %img{:alt => "", :src => image_url('topbutton.png')}/
:javascript
  $(function () {
      $(window).scroll(function () {
          if ($(this).scrollTop() > 250) $('#goTop').fadeIn();
          else $('#goTop').fadeOut();
      });
      $('#goTop').click(function () {
          $('body,html').animate({ scrollTop:0 }, 'slow');
      });
  });
:javascript
  $(document).ready(function() {
      if($.cookie('msg') == null)
      {
          $('#myModal').modal('show');
          $.cookie('msg', 'str');
      }
      else
      {
          $("div#myModal.modal").css('display','none');
      }


  });

:javascript
  jQuery('.slider').lbSlider({
      leftBtn: '.sa-left',
      rightBtn: '.sa-right',
      visible: 4,
      autoPlay: false,
      autoPlayDelay: 5
  });

:javascript
  jQuery(function(){

      jQuery('#camera_wrap').camera({
          fx: 'random',
          transPeriod: 500,
          time: 2000,
          height: '400',
          loader: 'false',
          pagination: true,
          thumbnails: true,
          hover: true,
          playPause: true,
          navigation: true,
          opacityOnGrid: false,
          imagePath: 'assets/images/'

      });

  });

releases/20150808023450/app/views/partials/_header.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %meta{:content => "Trường Trung Cấp Nghề Thủ Đức", :name => "description"}
    %meta{:content => "vnits.com.vn", :name => "author"}
    %title Trường Trung Cấp Nghề Thủ Đức
    %link{:href => "assets/images/favicon.png", :rel => "favicon"}
    %link{:href => "http://fonts.googleapis.com/css?family=Open+Sans:300,400,700", :media => "screen", :rel => "stylesheet"}
    = javascript_include_tag 'ckeditor/ckeditor.js'
    = stylesheet_link_tag    "bootstrap.min", :media => "all"
    = stylesheet_link_tag    "font-awesome", :media => "all"
    = stylesheet_link_tag    "bootstrap-theme", :media => "all"
    = stylesheet_link_tag    "style", :media => "all"
    = stylesheet_link_tag    "camera", :media => "all"
    = csrf_meta_tags
    = javascript_include_tag "modernizr-latest"
    = javascript_include_tag "jquery.min"
    = javascript_include_tag "fancybox/jquery.fancybox.pack.js"
    = javascript_include_tag "jquery.mobile.customized.min"
    = javascript_include_tag "jquery.easing.1.3"
    = javascript_include_tag "camera.min"
    = javascript_include_tag "bootstrap.min"
    = javascript_include_tag "custom"
	
    = javascript_include_tag "jquery.lbslider"
    = javascript_include_tag "jquery.cookie"
    :javascript
      var isMobile = {
        Android: function() {
            return navigator.userAgent.match(/Android/i);
        },
        BlackBerry: function() {
            return navigator.userAgent.match(/BlackBerry/i);
        },
        iOS: function() {
            return navigator.userAgent.match(/iPhone|iPad|iPod/i);
        },
        Opera: function() {
            return navigator.userAgent.match(/Opera Mini/i);
        },
        Windows: function() {
            return navigator.userAgent.match(/IEMobile/i);
        },
        any: function() {
            return (isMobile.Android() || isMobile.BlackBerry() || isMobile.iOS() || isMobile.Opera() || isMobile.Windows());
        }

      };
      

releases/20150808023450/app/views/partials/_hoatdong.html.haml
%section.news-box.top-margin
  .container
    %h2
      %span HOẠT ĐỘNG
    .slider
      .pre-next-slide-hoat-dong
        %a.sa-left{:href => "#"}
          %i.fa.fa-chevron-left.fa-2x
        %a.sa-right{:href => "#"}
          %i.fa.fa-chevron-right.fa-2x
      .clear-both
      %ul.list-unstyled.video-list-thumbs.row
        - all_video.each do |v|
          %li.col-lg-4.col-md-4.col-sm-12
            %a
              .video-container
                %object{:data => v.link, :type => "application/x-shockwave-flash"}
                  %param{:name => "movie", :value => v.link}/
                  %param{:name => "allowFullScreen", :value => "true"}
              %h5= v.caption

releases/20150808023450/app/views/partials/_muctieunghedt.html.haml
%section.container
  .row
    .col-md-t.box-.box-radius1.box-shadow
      .title-box.clearfix
        %h2.title-box_primary{:style => "margin-top: 0px;"} MỤC TIÊU PHÁT TRIỂN
      %div{:style => "padding: 9px;"}
        - if cauhinh_trangchu.each
          - cauhinh_trangchu.each do |c|
            = raw(c.muctieu)
        
    .col-md-4.box-.box-radius1.box-shadow
      .title-box.clearfix
        %h2.title-box_primary{:style => "margin-top: 0px;"} Các nghề đào tạo
      %div{:style => "padding: 9px;"}
        .list.styled.custom-list
          %ul
            - if cauhinh_trangchu.each
              - cauhinh_trangchu.each do |c|
                = raw(c.cacnghedt)
            

releases/20150808023450/app/views/partials/_navbar.html.haml
%body
  - all_popup.each do |p|
    #myModal.modal.fade.bs-example-modal-lg{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
      .modal-dialog.modal-lg
        .modal-content
          .modal-header
            %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
            %h4#myModalLabel.modal-title= p.caption
          .modal-body
            = raw(p.content)
  .navbar.navbar-inverse
    .container
      .navbar-header
        / Button for smallest screens
        %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => root_path}
          = image_tag "logo.png"
      .navbar-collapse.collapse
        %ul.nav.navbar-nav.pull-right.mainNav
          %li
            %a{:href => root_path} Trang Chủ
          - all_menu.each do |menu|
            %li.dropdown
              - if all_sub_menu(menu.id).length>0
                = link_to "#{menu.name}<b class='caret'></b>".html_safe ,menu_path(menu),{:class => "dropdown-toggle","data-toggle" => "dropdown" }
              - else
                = link_to menu.name ,"#"
              %ul.dropdown-menu
                - all_sub_menu(menu.id).each do |sub|
                  - if all_sub_menu(sub.id).length>0
                    %li.dropdown-submenu
                      = link_to sub.name,menu_path(sub)
                      %ul.dropdown-menu
                        - all_sub_menu(sub.id).each do |sub1|
                          %li{:style => " border-bottom: 2px solid #ffffff;"}= link_to sub1.name,menu_path(sub1)
                  - else
                    %li
                      = link_to sub.name ,menu_path(sub)
          %li= link_to "Liên Hệ",:controller => "contacts",:action => "new"

releases/20150808023450/app/views/partials/_notication.html.haml
- if flash
  - flash.each do |key,value|
    .red-mes
      %p= raw(value)

releases/20150808023450/app/views/partials/_slider.html.haml
%header#head
  .container
    .fluid_container
      #camera_wrap.camera_wrap.camera_emboss.pattern_1
        - all_slider.each do |s|
          %div{"data-link" => s.link, "data-src" => image_url(s.picture.url), "data-target" => "_blank", "data-thumb" => image_url(s.picture.url(:thumb))}
            .camera_caption= s.topcaption
     